---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{username}}-poi-backend-app-dev
  namespace: janus-argocd
  labels:
    argocd/app-name: {{username}}-poi-backend-app-dev
  annotations:
    argocd/app-name: {{username}}-poi-backend-app-dev
  # finalizers:
  #   - resources-finalizer.argocd.argoproj.io  
spec:
  project: default
  source:
    repoURL: https://github.com/Summit23Janus1/evanshortiss-backend-gitops
    targetRevision: HEAD
    path: ./helm/app
    helm:
      parameters:
      - name: "namespace.name"
        value: {{username}}
      - name: "image.repository"
        value: image-registry.openshift-image-registry.svc:5000/{{username}}/poi-backend-app
  destination:
    server: https://kubernetes.default.svc
    namespace: {{username}}
  syncPolicy:
    automated: 
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - RespectIgnoreDifferences=true
    - ApplyOutOfSyncOnly=true    
    retry:
      backoff:
        duration: 5s # the amount to back off. Default unit is seconds, but could also be a duration (e.g. "2m", "1h")
        factor: 2 # a factor to multiply the base duration after each failed retry
        maxDuration: 10m # the maximum amount of time allowed for the backoff strategy