---
apiVersion: v1
kind: Secret
metadata:
  name: {{username}}-poi-gateway-app-repo
  namespace: janus-argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://github.com/Summit23Janus3/ryanj3-gateway-gitops